@startuml
Client -> Server: Authentication Request
Server --> Client: Authentication Response
Client -> Server: Another authentication Request 
Server <-- Client: another authentication Response
@enduml

@startuml
participant Participant as Foo
actor Actor as Foo1
boundary Boundary as Foo2
control Control as Foo3
entity Entity as Foo4
database Database as Foo5
collections Collections as Foo6
queue Queue as Foo7

Foo -> Foo1 : To actor
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7 : To queue
@enduml


@startuml
actor Bob #red
'   Единственная разница между actor
'   и participant - это разная форма отображения
participant Alice
participant "у меня очень\nдлинное имя" as L #99FF99

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction 
@enduml

@startuml
participant Last order 30
participant Middle order 20
participant First order 10
@enduml


@startuml
Alice -> Alice: Это сигнал к самому себе. \nТакже это является демонстрирацией \n многострочного \n текста.
@enduml

@startuml
skinparam sequenceMessageAlign right
Bob -> Alice : Request
Alice -> Bob : Response 
@enduml

@startuml
skinparam responseMessageBelowArrow true
Bob -> Alice : дай пять евро
Alice -> Bob: нет, не дам
@enduml


@startuml
Bob ->x Alice
Bob -> Alice
Bob ->> Alice
Bob -\ Alice
Bob \\- Alice
Bob //-- Alice

Bob ->o Alice
Bob o\\-- Alice

Bob <-> Alice
Bob <->o Alice
@enduml


@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
@enduml


@startuml
autonumber 1.1.1
Alice -> Bob: Authentication request
Bob --> Alice: Response

autonumber inc A
'Now we have 2.1.1
Alice -> Bob: Another authentication request
Bob --> Alice: Response
autonumber inc B
'Now we have 2.2.1
Alice -> Bob: Another authentication request
Bob --> Alice: Response
autonumber inc A
'Now we have 3.1.1
Alice -> Bob: Another authentication request autonumber inc B
'Now we have 3.2.1
Bob --> Alice: Response
@enduml


@startuml
Alice -> Bob : message 1
Alice -> Bob: message 2

newpage

Alice -> Bob : message 3
Alice -> Bob : message 4

newpage A title for the \n last page

Alice -> Bob : message 5
Alice -> Bob : message 6
@enduml


@startuml
Alice -> Bob: Authentication Request
alt successful case

    Bob -> Alice: Authentication Accepted

else some kind of failure

    Bob -> Alice: Authentication Failure 

    group My own label
    Alice -> Log : Log attack start

        loop 1000 times
            Alice -> Bob: DNS Attack
        end

    Alice -> Log : Log attack 
    end

else Another type of failure

    Bob -> Alice: Please repeat

end
@enduml


@startuml
Alice -> Bob : привет 
note left: это первая заметка

Bob -> Alice: ara
note right: это другая заметка
Bob -> Bob : я размышляю над этим
note left
заметки
могут занимать несколько строчек
end note 
@enduml


@startuml 
participant Alice 
participant Bob
note left of Alice #aqua
Будет отображено 
слева от Алисы
end note

note right of Alice: Будет отображено справа от Алисы

note over Alice: Будет отображено над Алисой.

note over Alice, Bob #FFAAAA: Будет отображено\п над Алисой и Бобом.

note over Bob, Alice
А это еще 
один пример 
длинной заметки.
end note 

@enduml


@startuml

== Initialization ==

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

== Repetition ==

Alice -> Bob: Another authentication Request 
Alice <-- Bob: another authentication Response
@enduml


@startuml
Bob -> Alice : привет
activate Alice
Alice -> Alice : какое-то действие 
return пока
@enduml



@startuml
title __Simple__ communication example\non several lines

Alice -> Bob: Authentication Request 
Bob -> Alice: Authentication Response

@enduml


@startuml
box "Internal Service" #LightBlue 
participant Bob 
participant Alice 
end box 
participant Other

Bob -> Alice : hello
Alice -> Other : hello
@enduml



@startuml
Alice -> Bob: Запрос авторизации 
alt#Gold #LightBlue Успешный кейс
    Bob -> Alice: Запрос удовлетворен
else #Pink Ошибка
    Bob -> Alice: Запрос отклонен
end 
@enduml

###############################################################

@startuml

skinparam sequence {
    ArrowColor black
    ActorBorderColor black
}

actor User #LightPink

participant "Amazon" as Amazon #LightYellow

== Просмотр товаров ==
User -> Amazon: Просмотр продуктов
Amazon -> User: Отображение продуктов

== Добавление в корзину ==
User -> Amazon: Добавление товара в корзину
Amazon -> Amazon: Проверка \nналичия \nтовара  \nна складе

alt #LightBlue Добавление
    Amazon -> User: Подтверждение добавления в корзину
else #Pink Товара нет
    Amazon -> User: Товар не был добавлен в корзину \n по причине его отсутствия на складе

end

== Оформление заказа ==
User -> Amazon: Оформление заказа
Amazon -> User: Запрос на ввод данных доставки и оплаты

== Ввод данных доставки и оплаты ==
User -> Amazon: Ввод данных доставки и оплаты
Amazon -> User: Подтверждение ввода данных

alt #LightBlue Оплата
    User -> Amazon: Оплата заказа
    Amazon -> User: Подтверждение оплаты
else #LightYellow Возврат
    User -> Amazon: Запрос на возврат товара
    Amazon -> User: Инструкции по возврату
end

== Ожидание доставки ==
User -> Amazon: Ожидание доставки
Amazon -> User: Статус доставки

== Получение товара ==
User -> Amazon: Получение товара
Amazon -> User: Подтверждение получения товара

== Возврат товара ==
User -> Amazon: Возврат товара
Amazon -> User: Подтверждение возврата

@enduml